@Atrio.API_HostAddress = http://localhost:5289

GET {{Atrio.API_HostAddress}}/api/students
Accept: application/json

###

GET {{Atrio.API_HostAddress}}/api/classes
Accept: application/json

###

GET {{Atrio.API_HostAddress}}/api/attendance
Accept: application/json

###

POST {{Atrio.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@atrio.local",
  "password": "ChangeMe!"
}
